name: Sheets to JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        # Installation des deux modules requis pour la nouvelle méthode d'authentification
        run: npm install google-spreadsheet google-auth-library

      - name: Export sheets
        env:
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
          GSERVICE_EMAIL: ${{ secrets.GSERVICE_EMAIL }}
          GSERVICE_KEY: ${{ secrets.GSERVICE_KEY }}
        run: node scripts/export.js

      - name: Commit and Push JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/*.json
          # Le "|| exit 0" évite que le workflow ne plante s'il n'y a aucun changement dans les données
          git commit -m "Update data from Google Sheets" || exit 0
          git push
